schema_version = "1.0.0"

# Example of manifest file for a Blender extension
# Change the values according to your extension
id = "LZ_VRM_Blendshape_Tool"
version = "1.0.0"
name = "VRM Blendshape Tool"
tagline = "Quickly generate blendshape proxies from shapekeys on your meshes"
maintainer = "lunazera"
type = "add-on"
website = "https://github.com/Lunazera/Blender-VRM-Blendshape-Tool"

blender_version_min = "3.0.0"

license = [
  "SPDX:GPL-3.0-or-later",
]